development:
  adaptor: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
|
test:
  adaptor: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
|
production:
  adaptor: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
|
